### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by weird-dreams** [malxau/yori#13]
Hi there,
you do not provide an UNINSTALL.
Please describe what to do to get Yori from my machine..

**Comment by malxau** [comment]
Yori doesn't write things around the machine except as instructed.  The best way to remove it today is to just remove the directory it was installed to - use cmd to run ```rd /s/q "C:\Program Files\Yori" ``` or similar.

I'll look into what it takes to have a true uninstall that removes things like shortcuts that were requested when ysetup runs, and where the uninstaller program will request Windows to delete it on next restart (since it can't delete itself.)

**Comment by malxau** [comment]
1.20 is released with an uninstaller, although I'm not really happy with it and will probably keep looking at it more.

It is designed to be operated via control panel, and appears to work okay in that case.  Unfortunately it can't delete in use binaries, and the "official" way to do this is to defer deletion to the next reboot, but that implies Administrator access.  This sucks because a non-admin can install it.  What I've seen on the Internet for how others do this is to launch a cmd process to schedule a future delete after the process terminates, which seems incredibly hacky.

I also found after releasing 1.20 that launching uninstall from within the Yori shell is a bad idea, because the shell process is in use, which causes it to fail to uninstall yori-core, and it leaves things in a messed up state.  I'll look into improving this.

**Comment by malxau** [comment]
I just released 1.21 which I believe improves things with better errors when trying to uninstall Yori from within itself.  The installer makes registering an uninstall handler optional for users who want installation without registry modifications.  If you find any additional problems, please either reopen this issue or file a new one describing that problem.  Thanks for the report!
