### ISSUE TITLE
GNU Readline-style TAB completion

### ISSUE THREAD

**Issue by dmitri-gb** [malxau/yori#14]
Would it be possible for Yori to use GNU Readline-style TAB completion, where suggestions are shown as a list below the prompt, instead of immediately being inserted at the cursor position? [Clink](https://github.com/mridgers/clink) also does this.

Also, when a directory name is inserted during auto completion, the trailing slash should also be appended at the end. This makes it easier to navigate into deep directory structures, as you don't have to type `/` or `\` after each completed name.

**Comment by malxau** [comment]
For the first issue, I coded something up based on my understanding of how bash would do this, but it doesn't work as well due to differences in escaping between the two shells.  Bash will always escape spaces using its escape character, so it becomes possible for the user to type characters at the end of the string to indicate which match to follow.  Yori is expecting things like argument quotes when spaces are present, which means the only way to select a match might be to traverse earlier in the string to type a quote, then later in the string to enter new characters to select a match.  This experience is very clumsy.  I haven't looked at Clink, but note that CMD's argument parsing is horrifically inconsistent so it's very hard to define any rule to follow - eg `cd C:\Program Files` (without quotes) works but `dir C:\Program Files` will not, and `dir C:\Program^ Files` also won't, etc.

For the second point, I coded something up and pushed it to master.  Personally this behavior in PowerShell drives me nuts, although since it's used there any many people might find it familiar, it makes sense to at least include.  This can be enabled with `set YORICOMPLETEWITHTRAILINGSLASH=1` .

**Comment by malxau** [comment]
I've been thinking more about this, and digging a level deeper, it looks like the difference is between the way Windows and Linux communicate command lines to child processes.  In Linux, the command line is a buffer which contains NULL terminators between each argument (ie., the shell indicates to the child where the argument breaks are.)  In Windows, the command line is a buffer that the child process gets to parse to find where the argument breaks are.  Shell escapes in the Windows case carry no meaning, because the whole point is for the shell to consume them - meaning the child process has no indication where the argument break needs to be.  That's presumably why Windows settled on quotes rather than escapes to handle file names with spaces.

I think I'll clean up what I wrote and push it regardless, but it doesn't seem that great when spaces are present in file names.

**Comment by malxau** [comment]
I pushed to master an implementation of bash-style completion.  This can be enabled with `set YORICOMPLETELISTALL=1`.

**Comment by dmitri-gb** [comment]
This looks great! Thanks!

One thing that Clink does, is that it automatically inserts a quote at the beginning of the argument whenever the completion list contains at least one item with spaces. This has worked quite well for me so far. Perhaps Yori could do the same?

**Comment by malxau** [comment]
I pushed a change that does something like you described.

**Comment by malxau** [comment]
1.20 is released with these changes.  Let me know if there are any issues.
