### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by kobrad** [malxau/yori#2]
Any kind of attempt results in "Could not locate selected package files".

![yori_error](https://user-images.githubusercontent.com/11524292/52281652-d644ab80-295e-11e9-8251-8643dcd4fd30.PNG)

**Comment by malxau** [comment]
This happens if the installer doesn't have network connectivity.  The most common reason for this today is overzealous antivirus products that "protect" you by failing accesses from programs that they don't explicitly trust, and Yori is far too small for AV companies to do that for.  Do you have an AV product installed, and if so, which one?  Another possibility is a proxy server, although Yori connects to the internet via the same HTTP stack as Internet Explorer, so if proxies are configured correctly for the user it should still work.
