### ISSUE TITLE
Backspacing after newline misbehaving

### ISSUE THREAD

**Issue by cbrit** [malxau/yori#23]
I am using Windows Terminal Version 0.8.10261.0

When a new line is required to wrap a command, if I backspace such that the cursor should return to the original (first) line, it works the first time, but if I repeat this such that the cursor need to go to the next line again it adds an _additional_ newline and begins printing two lines below the beginning of the command. The behavior is little unpredictable as it seems to change based on the width of the window. I probably explained that very poorly, so here is a gif of the behavior:

![yoribug](https://user-images.githubusercontent.com/23322838/74354754-6e028400-4d81-11ea-8ea9-6741fb3d48d6.gif)

**Comment by cbrit** [comment]
I realize this could be a Windows Terminal bug, the reason I assumed it was an issue with Yori is that my other shells were not having the same issue.

**Comment by malxau** [comment]
Thanks for the report.  This looks like a Windows Terminal bug to me.

The background is that shells like CMD ask the console for a line of text, so positioning the cursor is a problem for the console/terminal.  Bash uses VT sequences and can reason about entered text as a 1 dimensional array of text.  Win32's low level support, which Yori uses, exposes the console/terminal as a 2D array of cells, and Yori is responsible for putting the right things in the right places and positioning the cursor.  In order to do this, every time a key is pressed, it bases logic off the current location of the cursor; this isn't ideal but it's done because if the window is resized the text and cursor can be moved around, so the cursor provides an anchor point around which to render.  And WT places the cursor in the wrong spot in certain cases.

Another additional piece of background is that the traditional Windows console, when writing the final cell in a line, moves the cursor to the next line.  Linux moves the cursor to an invisible cell that's beyond the current line but not on the next.  The Windows 10 console, with VT support enabled, ends up trying to create a middle ground where writing the final cell doesn't move the cursor anywhere, but it remembers that the next cell to write is on the next line.  This behavior messes with Yori pretty badly, and Yori turns it off (in a commit after 1.20, sigh.)

The behavior here makes me wonder if WT is trying to tackle the same problem in a different way and isn't getting it quite right.  To see this behavior in Yori, slowly enter text, until you type a character that moves the cursor to the next line.  Then, hit backspace, and look where the cursor is.  For the final cell of the line, the cursor somehow manages to be advanced by one space, which confuses everything that follows.  Stepping through in a debugger, this happens when calling FillConsole APIs, which aren't supposed to move the cursor anywhere.  Aside from messing up rendering, it means the cells being manipulated on the display are not the same characters being manipulated in the memory buffer, so the line that you see is not the line that you get.

I've opened microsoft/terminal#4561 for this with a targeted demo program.

**Comment by cbrit** [comment]
Hey thanks for the quick response and raised issue! Looks like they have a fix in the next release already that I didn't find.

**Comment by malxau** [comment]
It looks like 0.9 is released now including the fix, so there's nothing more for Yori to do here.  Closing.
