### ISSUE TITLE
Building sources using CL.exe v12.00.8804 and v19.16.27034

### ISSUE THREAD

**Issue by aleaksunder** [malxau/yori#32]
Long story short... I was trying to build all sources in in order to achieve less "false positive" effect on VirusTotal, but that's not the point!

I have tried VS 6 , Windows 7 DDK, 2010 and 2019 tools ( actually 2015 , 2017 built in 2019 ) and was not being able to build from scratch without any warnings/errors/app crashes in VS 6 and all 2019 built-in stuff.

All of later is only for x86 platform

Input: `BuildVS6.cmd`
```
chcp 850
SET "LIB=%ProgramFiles(x86)%\Microsoft Visual Studio\VC98\Lib"
SET "PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\VC98\Bin;%PATH%"
SET "INCLUDE=%ProgramFiles(x86)%\Microsoft Visual Studio\VC98\Include;%Include%"
CHDIR /D "C:\Sources\yori"
nmake
```
VS 6 output to mention:
```
*** Compiling pkglib
api.c
backup.c
create.c
install.c
reg.c
remote.c
util.c
Generating Code...
remote.c(1565) : warning C4701: local variable 'NewerVersionAvailable' may be used without having been initialized
remote.c(1565) : error C2220: warning treated as error - no object file generated
NMAKE : fatal error U1077: 'cl' : return code '0x2'
Stop.
```
I understand that this is just a warning, but maybe it will help to solve something, since this warning is in `yoripkg` and may be this leads into false positive... sorry if this is completely silly but I am not a senior developer, not even an intermediate, just know that sometimes very little things leads to very huge problems)

And this is not the point for me since I do not need to work with VS 6 at all... But the second one is really what bothers me

VS2019 story.
Input: `build.cmd`
```
chcp 850
CALL "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86 -vcvars_ver=14.16
CHDIR /D "C:\Sources\yori"
nmake
```

Since I was able to build all source without any warnings/errors in VS 2019 Community with 2017 tools installed, since the goal was to build all stuff, that can work on XP, and 2017 compiling tools is able to do so, or maybe I am totally do not understand something) So I build source and it runs well untill I have entered `dir` command and `dir.exe` crashed on clean XP SP3 without any updates, and I decide to dig a little in) By the way `oneyori.exe` crashed in the same way on entering `dir` command ( and later tests I have done mostly with `oneyori.exe` )

Therefore I've built the Debug version of source and... nothing crashed at all ))) That was funny)) Finally I have figured out that `makefile` compiler option `-O1sb1` is to be blamed) After that I have tried `-O2` and builded exe crashed, after that I build with `-Ox` option and `dir` do not crashed but there was a strange behavior in output, I do not even know how to describe it... just take a look:
![image](https://user-images.githubusercontent.com/40979373/77403033-8e931480-6dea-11ea-8552-e29639de9618.png)

`-Ox` seems not to works properly and... I have noticed the same behaviour when trying to build with 2015 VS tools, without any `-O` swith modification, so by default with `-O1sb1` VS2015 tools provides binaries with the same output problems as VS2017 with `-Ox`

I have firured out that only `-Od` switch on VS2017 tools provides stable binary at least for `dir`, I assume there maybe more not working stuff, but now the only thing I saw is `dir`.

And the correct output is^ 
![image](https://user-images.githubusercontent.com/40979373/77403602-65bf4f00-6deb-11ea-9f93-f326a913989f.png)

So finally I have built DEBUG version with VS2017 Tools with `-O1sb1`, started `oneyori.exe`, attached debugger to it, entered `dir` command and here is what I've got:
![image](https://user-images.githubusercontent.com/40979373/77404133-3e1cb680-6dec-11ea-9dca-af1428e7b42c.png)

Sorry for such a long message... just trying to decribe as completely as possible)

P.S. I think you will find that funny)
All that `chcp 850` stuff in my batch script is only to switch codepage to 850 since `cl.exe` is locale-dependend and your makefile doesn't work by default on any non-english system with region-dependent locale)) That was confusing but nobody have been surprised) *facepalm*

**Comment by malxau** [comment]
That's a very good diagnosis for somebody who claims to be "not even an intermediate."

For the first issue, this is a trivial fix.  Compilers trying to detect uninitialized variables are heavily dependent on the optimizations they've performed.  I'm a little surprised by this particular compiler though, because I use VC6 SP5 to generate all of the 32 bit builds of Yori, so it's the one that seems least likely to have this problem.  Sigh.

The second issue is surprising to me but probably shouldn't be.  The background here is that Yori is trying to avoid using MSVCRT style runtime DLLs, so that it can be compiled with newer compilers and run on old versions of Windows, and doesn't require any fancy installation no matter what compiler is used.  One of the many things these DLLs provide is 64 bit math support for 32 bit processors.  These routines are special because they use nonstandard calling conventions and must be written in assembly.  There's a pile of different routines for different purposes.  One set, the dvrm ones, are attempting to exploit a CPU optimization where the Intel instruction for divide can return both the truncated divided value as well as remainder in a single instruction.  This is a nice optimization, but it's of limited value, because software often only cares about one or the other, not both.  So it's kind of rare to see compilers try to use this function, but this compiler did.

My implementation of it does not attempt to optimize anything, and is really quite inefficient.  It just tries to translate the call into a division call and a remainder call, but needs to shuffle the results around between registers to honor the calling convention.  I used the esi register, but the compiler was expecting the esi register to be preserved across the call, and it was used to remember the index within the string that should be populated.  So the cell that gets populated ends up being determined by the low 32 bits of the remainder of the division.

I pushed fixes for both of these now.

Finally, can you explain more about the Makefile code page issue?  I tried using cmd with a couple code pages but haven't observed a build failure.  Which code page do you normally use?

**Comment by aleaksunder** [comment]
Nice! I can confirm that both issues are gone now.
By the way if I am not wrong it was VS 6 SP6 + KB957924 v2 in the first issue
Now all compiles and runs without crashes

Makefile story:
I can not give you exact point at which version Microsoft begins to provide locale-dependent output for it's CL.exe compiler but I think this was done firstly in VS 2005 or VS 2008
Technically this was realized through the MUI dll's ( as everything in Windows )and I believe you can not even reproduce this since you do not have localized version of Visual Studio or maybe just Visual Studio Tools installed on localized version of Windows

Here is the Tools folder contents:
```
 Directory of C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86

20.03.2020  13:06  <DIR>             .
20.03.2020  13:06  <DIR>             ..
20.03.2020  13:06  <DIR>             1033
20.03.2020  13:06  <DIR>             1049
20.03.2020  13:03            167,296 atlprov.dll
20.03.2020  13:03             85,968 bscmake.exe
20.03.2020  13:03          1,913,216 c1.dll
20.03.2020  13:03          6,252,416 c1xx.dll
20.03.2020  13:03          6,408,568 c2.dll
20.03.2020  13:03            356,264 cl.exe
20.03.2020  13:03                409 cl.exe.config
20.03.2020  13:03            546,688 CppCoreCheck.dll
20.03.2020  13:03             40,928 cvtres.exe
20.03.2020  13:03          3,706,048 d3dcompiler_47.dll
20.03.2020  13:03          1,354,624 dpcmi.dll
20.03.2020  13:03             20,376 dumpbin.exe
20.03.2020  13:03             20,376 editbin.exe
20.03.2020  13:03          2,275,712 EspXEngine.dll
20.03.2020  13:03            160,640 ifc.exe
20.03.2020  13:03             20,376 lib.exe
20.03.2020  13:03          1,412,008 link.exe
20.03.2020  13:03                409 link.exe.config
20.03.2020  13:03          5,523,632 LocalESPC.dll
20.03.2020  13:03            159,504 Microsoft.Diagnostics.Tracing.EventSource.dll
20.03.2020  13:03             55,440 Microsoft.VisualStudio.RemoteControl.dll
20.03.2020  13:03            795,688 Microsoft.VisualStudio.Telemetry.dll
20.03.2020  13:03             41,104 Microsoft.VisualStudio.Utilities.Internal.dll
20.03.2020  13:03            484,256 ml.exe
20.03.2020  13:03            103,296 msobj140.dll
20.03.2020  13:03            287,104 mspdb140.dll
20.03.2020  13:03          1,092,032 mspdbcmf.exe
20.03.2020  13:03            481,152 mspdbcore.dll
20.03.2020  13:03            131,488 mspdbsrv.exe
20.03.2020  13:03            461,696 mspdbst.dll
20.03.2020  13:03          1,858,432 mspft140.dll
20.03.2020  13:03          1,034,112 msvcdis140.dll
20.03.2020  13:03            449,824 msvcp140.dll
20.03.2020  13:03             28,960 msvcp140_1.dll
20.03.2020  13:03            173,344 msvcp140_2.dll
20.03.2020  13:03            535,424 Newtonsoft.Json.dll
20.03.2020  13:03             99,760 nmake.exe
20.03.2020  13:03             62,440 pgocvt.exe
20.03.2020  13:03             81,656 pgodb140.dll
20.03.2020  13:03             92,072 pgomgr.exe
20.03.2020  13:03             49,408 pgort140.dll
20.03.2020  13:03             67,520 pgosweep.exe
20.03.2020  13:03             22,440 undname.exe
20.03.2020  13:03             96,128 vcmeta.dll
20.03.2020  13:03             80,672 vcruntime140.dll
20.03.2020  13:03            284,152 vctip.exe
20.03.2020  13:03             41,408 xdcmake.exe
20.03.2020  13:03                409 xdcmake.exe.config
          48 File(s)         39,416,875 bytes
           4 Dir(s)      28,237,074,432 bytes free
```

As you can see there are to directories `1033` and `1049`... One is for English MUI and second one for Russian MUI, and the CL.exe itself somehow relies not on any registry setting but on codepage of the environment from which it was started, and than it uses appropriate MUI dll to do the output, at least CL.exe v19.x do it that way... So in my exact situation default codepage is 866 (Cyrillic) and therefore CL.exe uses dll from 1049 directory and I have russian output from it.

And since your make file depends on output of the compiler itself at least at theese lines:
https://github.com/malxau/yori/blob/c4e00a5f8b1d0b83b9a10cbb7a84adb430cc3468/Makefile#L7-L29
But my output is not in English and therefore output does not contain word "for " theese lines does not work at all, so changing codepage of environment saved me the day) Maybe it's enough to remove "for<space symbol>" from Makefile, but multiple places of `config\common.mk` relies on output from the compiler too, so maybe one little batch file in sources will remove this issue at all... something called `build.cmd` which have to be runed from initiated and configured by user Visual Studio Developer Command Promt with contents like this:
```
@SETLOCAL EnableDelayedExpansion
@PUSHD "%~dp0"

@CHCP 850

@START "Make" /D "%~dp0" /B /WAIT "nmake.exe"

@PAUSE

@POPD
@ENDLOCAL
@EXIT /B
```

**Comment by malxau** [comment]
Thanks.  Windows language packs are freely downloadable, as are Visual Studio languages.  After messing around for a bit, I was able to get the same environment you had, although it required changing the system language (not the user language) to get there.

I pushed a change which fixes most of the cases that I can see.  Unfortunately I don't have a perfect test matrix, because I have new non-English, new English, and old English compilers (ie., no old non-English compilers.)  The build checks are mainly about changing compiler and linker behavior where options are available, so old non-English compilers would be an interesting test case.

Anyway, let me know if there's anything more needed in this issue or if it can be closed.

**Comment by aleaksunder** [comment]
Yes, I can confirm that all works fine at least on russian Windows... Thank a lot!
It is nearly impossible for one man to test all combinations of system locales and compiler versions, so I think the "chcp" trick can be mentioned in documentation or somekind of readme for those who trying to build yori and struggling to do so somewhere in Trinidad and Tobago =)

I think codepage 850 is not default for the native US English and I assume codepage 437 is...
So `CHCP 437` command mentioned in readme can help someone
