### ISSUE TITLE
Ctrl + Arrow getting ignore under Windows Terminal

### ISSUE THREAD

**Issue by drhaas** [malxau/yori#34]
Windows Terminal has support for Ctrl+Arrow movement in the command line, which yori also has. They seem not to be working well  together.

Is there a way to disable it in yori that I did not find?

I have reproed this with yori 1.20 and 1.21 and multiple versions of Windows Terminal.

Thanks for the great work. I really enjoy yori.

**Comment by malxau** [comment]
Can you describe a little more about what happens when they are used together, and what behavior you'd like to see?  I tried this just now and Ctrl+left and Ctrl+right seemed to work as expected in Yori and CMD under WT.

I'd be very surprised if it's possible to just disable it in Yori.  As far as I know, a command line program has a choice between asking the Terminal to give it a line of text (so the Terminal implements all line navigation and editing features), or it can ask for all raw keystrokes and implement all of the line editing logic itself.  Yori went with the latter route in order to provide simple enhancements like flexible tab completion.  But having done so, there's no way on a per-keystroke basis to invoke the Terminal's line editing logic - the buffer being edited is completely owned by the Yori process.

**Comment by drhaas** [comment]
You're right. It's working just fine. Maybe an older version (of Windows Terminal) had an issue. Thanks for looking into it.
