### ISSUE TITLE
Settings File

### ISSUE THREAD

**Issue by Skibicki** [malxau/yori#4]
Please add a settings file for auto-loading various settings and aliases.

**Comment by malxau** [comment]
The reason I hadn't done this is because in Windows (and with CMD) this is normally done by updating the shortcut to add "/k script.ys1" or similar to the end.  This allows you to have many shortcuts with many different settings.

Obviously adding a facility to auto-execute a single script would be fairly simple, but it doesn't seem as nice as what can be currently done without it.  I can do this if people want it, but it won't be something I'd be likely to ever use.

**Comment by Skibicki** [comment]
Normal settings files would be redundant when scripts can accomplish more advanced tasks.  Batch style scripting would be useful to learn and I should do that.

**Comment by malxau** [comment]
I thought about this and given you're not the first person to ask went ahead and coded something up.  As of this writing, in master, if there's a YoriInit.* file in your home directory, it will be executed on start.  If not, and there's one next to the yori.exe executable, it will be executed on start.  Typically these would be YoriInit.ys1 (ie., a Yori script) but it would also somewhat work to use a .cmd script since Yori will reload the environment and aliases after executing one.

**Comment by mixmastamyk** [comment]
This is definitely needed.  However, whatever you decide it needs to be documented.  I've been scouring the net and now the source code to figure out how to get a settings to last.  Not a great experience. 😂

Thanks for the hard work.

**Comment by malxau** [comment]
Sorry, I hadn't realized that I forgot to document this.  It's documented now at:

http://www.malsmith.net/yori/guide/#script_autoinit

Let me know if it needs clarification.

**Comment by mixmastamyk** [comment]
Yes, appreciated thanks.  The important parts are there but it feels a bit abstract to someone new.  A concrete example would be nice.  

For example, create a file at: 

    "%USERPROFILE%\yoriinit.ys1"

With example text:

    # yellow prompt
    set YORIPROMPT=$E$[33;1m$P$$G_OR_ADMIN_G$$E$[0m

    # some aliases
    alias -s dir=dir -color $*$
    alias -s cat=type $*$

As another example:

>  Note that as with CMD, it is often useful to have per-shortcut settings. This can be   
>  accomplished by adding "/k path_to_script.ys1" to the arguments in the shortcut.

This is missing the executable name required to make it work.  I had to look up what the main exe file name was:  `"yori.exe /k path_to_script.ys1"`

I also struggled for about ten minutes because I thought the filename extension was `.ysl` (el) when it has to be `.ys1` (one) to work.
