### ISSUE TITLE
Redirection is broken

### ISSUE THREAD

**Issue by xenu** [malxau/yori#5]
```
C:\Users\xenu\Documents>ver
YoriLib version: 01.00
Yori shell version: 01.00
Build date: Apr 30 2019
C:\Users\xenu\Documents>osver
▄▄ Windows version: 10.0.18362 (unknown), AMD64
C:\Users\xenu\Documents>echo a > b.txt
CreateProcess failed (3): The system cannot find the path specified.
```
It doesn't matter what command I try to redirect, it's always failing with the above error message.   Output filename and directory also seem to be irrelevant.

**Comment by malxau** [comment]
Hi xenu,

Traditionally Yori expected there to be no space between the redirection operator and the target file.  Taking the expression "echo a > b.txt", Yori is parsing this expression as "invoke 'echo a b.txt', and redirect to empty string."  It can't resolve empty string, and fails.

You are not the first person to have been surprised by this behavior, so since 1.0, there have been a few changes. [Commit 04f5210c7e50f9d524624141148d46cd9b69071d](https://github.com/malxau/yori/commit/04f5210c7e50f9d524624141148d46cd9b69071d#diff-77cbc257e66302866cf6191754c0c8e3) allows spaces between the redirect operator and the file, so the expression you typed would work in builds from master or the next release.  In addition, [commit 64f7adc76a1fc3a04064ee655162308fcee3b4f8](https://github.com/malxau/yori/commit/64f7adc76a1fc3a04064ee655162308fcee3b4f8#diff-77cbc257e66302866cf6191754c0c8e3) updates the error message to indicate that any failure occurred as part of redirection rather than launching the process, so make any future similar failures easier to understand.

Thanks for trying Yori, and please keep reporting other issues you encounter.

**Comment by malxau** [comment]
Also, [commit 942c69acc05fb5b2e7ab670369402648cf1694b5](https://github.com/malxau/yori/commit/942c69acc05fb5b2e7ab670369402648cf1694b5) should ensure that osver no longer reports the build as unknown.

**Comment by xenu** [comment]
Thank you, I'll wait for the next release.

**Comment by malxau** [comment]
These fixes are all released now.  Let me know if you hit further issues.
