### ISSUE TITLE
Use a different installer

### ISSUE THREAD

**Issue by cup** [malxau/yori#6]
http://malsmith.net/download?obj=yori/latest-stable/win32/ysetup.exe

cant be extracted with InnoExtract or 7-Zip in a meaningful way.

It would be better to have this, or to simply offer a zip build with the
executable.

**Comment by malxau** [comment]
ysetup is a stub installer that downloads the packages you select and installs them.  It can't be extracted because it doesn't have a payload.

If you'd like to obtain the raw packages, after performing a core install run "ypm -rl" which will list the URLs of each of the packages on the server.  These are compressed using the .cab format, which should be openable in explorer or via the expand.exe command line tool which is included in Windows.

If you want to be able to install from an offline set of packages, see the section on "mirrors" at http://www.malsmith.net/yori/guide/#updating .

**Comment by cup** [comment]
http://www.malsmith.net/download/?obj%yori/latest-stable/=c:\local\packages\

404 Not Found

**Comment by malxau** [comment]
Quoting the paragraph above that line:

> Ypm can also mirror packages, re-routing requests destined to one source to another source. To do this, add a [Mirrors] section in packages.ini with each line containing a value to substitute with another value. The '%' character can be used to indicate an '=' character, which is otherwise inexpressible because it delimits the value to replace with the new value to use. For example, to remap malsmith.net packages to a local location, use:

So that line includes a source URL to map from and a target path to map to, which in this case is "c:\local\packages".  "C:\local\packages" is not a server resource, and it is expected that the server would return 404 if it were requested.

**Comment by cup** [comment]
how to get the raw packages without installing anything?

**Comment by malxau** [comment]
The reason I suggested performing a core install first is to provide a mechanism to query the server to find out what packages it contains.  At a pinch you could probably just look at the list from http://www.malsmith.net/download/?obj=yori/latest-stable/pkglist.ini , and assemble the URLs from that.  Obviously this is only looking at the latest stable yori release, not anything else the server might host or refer to.

Using ypm -rl is just automating this process into something that's easier to use, easier to support, and more correct.

**Comment by cup** [comment]
to any interested, here is example URL

http://malsmith.net/download?obj=yori/latest-stable/yori-core-amd64.cab

**Comment by malxau** [comment]
Ok, just out of curiosity, I have to ask...

If you trust the binary code, why not run "ypm -rl" to get the full list in a way that will work over time?
If you do not trust the binary code, why would you want to download the binary packages?

**Comment by cup** [comment]
I trust the packages, but not the installer.

Binary packages are just dumb files, they typically dont do anything beyond their main purpose.

But installers can be nefarious, either intentionally or from lazy coding. They can add registry entries, modify environment variables, add start menu entries.

I dont want any of that at this point, as I dont know if I even like the software. In my case ZIP or CAB file is a simple and more trusted way to test new software.

**Comment by malxau** [comment]
That makes sense, I feel the same way, and ysetup was written in that mindset.  If you haven't launched it, this is what it looks like.  All the things you're referring to are on the right, optional, and disabled by default:

![image](https://user-images.githubusercontent.com/17101641/60910665-44efa300-a236-11e9-84b6-10ab3e8ccc9e.png)

Also, just checking the source code, ysetup is the only thing in the source tree that interacts with the registry directly.  It modifies if the "add to path" options are selected, and queries in order to find the location of Program Files.

**Comment by cup** [comment]
@malxau nice! thanks for the info! maybe I will give the installer a try, since it is well behaved

I would only add that it might be helpful to link to `pkglist.ini` in the docs for any who might want manual install

thanks again

**Comment by malxau** [comment]
Obviously there's not really much I can do to make this work nicely without code, but:

- Commit c517bc3bcc8b4a1a6664af020349a3366eb1cf32 allows ypm to download an entire package set to a local directory
- Commit 3eeeaeec4d8cfd93e7c434b24bcaf1432270755d allows ysetup to install from a local directory of packages

Note that packages are currently just collections of files; there's no support in ypm for registry changes, shortcut creation, etc.  It's just laying out files and installing links to them in an .ini file in the same directory.

**Comment by muv1** [comment]
https://github.com/malxau/yori/issues/21

https://github.com/malxau/yori/issues/6
https://github.com/malxau/yori/issues/8

**Comment by avih** [comment]
> I dont want any of that at this point, as I dont know if I even like the software. In my case ZIP...

I feel the same.

Is there a reason to not provide a zip with all the utilities, for those who are interested in such thing?

I would guess that you too, when you want to try something which you didn't write, would prefer to get a zip, extract it yourself and try it out in that dir, instead of downloading a downloader which you need to run in order to try the thing, which might change things at the registry etc (even if your tool doesn't, and even if that 3rd party tool also doesn't).

You will not be the first to provide a zipped package without an installer/setup/downloader ;)

**Comment by malxau** [comment]
Thanks for looking into this.

 

For which files to include, see the `*.lst` files in the `pkg\` subdirectory.  These map the file name in the build tree to the file to install on the target machine.

 

`YoriInit.d` is probably the most important.  Also the `completion\` files are copied from the source tree to the destination (they’re not compiled.)  `modules` and `yorimin.exe` can just be removed – this was to prove a point that all builtin commands could be DLLs, but the regular `yori.exe` still has them statically linked in anyway.  Similarly, `oneyori.exe` is a version with (almost) all external commands linked in – it can be used standalone, but if all of the tools are there, it can also be deleted since it’s redundant.

 

Visual C++ 6.0 should work fine.  The “official” 32 bit builds use it, since it can still target NT 3.1 without special hacks.

**Comment by avih** [comment]
> For which files to include, see the `*.lst` files in the `pkg\` subdirectory.

> `YoriInit.d` is probably the most important.  Also the `completion\` files are copied from the source tree to the destination (they’re not compiled.)  `modules` and `yorimin.exe` can just be removed

Thanks,

So will you consider releasing a "portable" zip package (or packages) in addition to the installer?
