### ISSUE TITLE
RENAME command moves file or folder

### ISSUE THREAD

**Issue by aleaksunder** [malxau/yori#71]
Hello!

Since RENAME command is interpreted by "ymove.exe" utility it moves files and folder when it is not supposed to happen. Here is an example:

```
RENAME "C:\foo\bar" "bar.old"
```
If directory "C:\foo\bar.old" already exist than this command will move "bar" folder into "bar.old" folder and finally we will have "C:\foo\bar.old\bar" folder

By the way Windows "cmd.exe" correctly distinguish theese two commands: MOVE will end with the same result, but RENAME will end with error, saying that file already exist

Maybe it is safe to make "yrename.exe" utility that will interpret RENAME command separately

**Comment by malxau** [comment]
I wouldn't be so hasty in deciding what is correct here.  My goal in writing Yori wasn't to clone CMD, because replicating it would be pointless; my goal was to do something that kept the things that made sense and was willing to change things that don't.

I'm a bit curious why this behavior is desirable to you in 2020.  Honestly, I spent very little time thinking about this, because the reasons for it are all pre-1985 and it seems like a relic so old that it would make no sense to the vast majority of users today.

As far as I know, this happened because DOS 1 (1981) had no directories; DOS 2 (1983) added support for directories; DOS 3 (1984) updated the rename API to rename directories as well as files, but command.com was artificially crippled to only rename files for compatibility.  After this time, there were tools that renamed directories by simply invoking the DOS API (I wrote one.)  Later, DOS 6 (1993) bundled move.

In NT, the Win32 rename API is MoveFile, which makes no distinction between directories and files, and any program written for it (file manager, explorer, powershell) will make no distinction because they'd have to go out of their way to make it.  Tools arriving from other platforms won't make the distinction, because it is an artifact of DOS-specific limitations.  I haven't looked, but I'll bet CMD works by invoking undocumented-for-usermode functions like NtCreateFile with FILE_NON_DIRECTORY_FILE and NtSetInformationFile to perform the rename.

So I guess what I'd like to know is, what is the use case for wanting to distinguish files from directories in this way?  If there is a compelling use case, are you really saying that this what most users would want most of the time to justify making it default?

**Comment by aleaksunder** [comment]
My point is that it is not obvious behavior. So if I write script and use RENAME command personally I expect to get an error if rename operation is not possible for example due to file or forlder with the same name already exist.
If folder with that name already exist I will get MOVE operation and there is no way to know about it since MOVE will return 0 exit code.

Here is simple scenario for backup... I want to make a new folder, and want to be sure that if that folder already exist I need to save it and it contents. So I write it this way in CMD using Yori utilities since it is brillant idea to do everything with "\\?\" prefixes :
```
    "%yori_path%\fscmp.exe" -d "C:\foo\bar"

    IF NOT ERRORLEVEL 1 (

        "%yori_path%\ymove.exe" "C:\foo\bar" "C:\foo\bar.old"

        IF ERRORLEVEL 1 (

            ECHO ERROR
            EXIT /B 1

        )

    )

```
And there becomes a mess... If "C:\foo\bar.old" already exist I need to backup it too, and simply rename it to "C:\foo\bar.old-1" or whatever, but what if "C:\foo\bar.old-1" already exists? =) And this way "problem" gets recursive.
So MOVE operation is undesirable simply because it moves folders to other folders in this situation.

Please do not get me wrong. I just have three personal points of view:
1. When used or typed RENAME command is expected to only rename file or folder and especially do not move folder in another folder
2. I think nobody actually use RENAME command at all, or at least absolute majority of users use MOVE command, so I do not think that this can be script breaking change
3. Obvious behavior for me is better

I understand that maybe I am wrong and this behavior of MOVE command is historical and absolutely expected by everyone.
So this is just my point of view.

**Comment by malxau** [comment]
I'm sorry, I completely misread and misunderstood you.  Sorry for wasting your time and making you explain this twice.  I'll look into what I can do about this tomorrow.

**Comment by aleaksunder** [comment]
No problem!
I just want add one thought: I do not remember where exactly I've seen this... But one file/folder copy program ( FastCopy I suppose ) distinguishes final targets for copy/move operations by last slash in the target path... It was very handy! For example:

```
copy "C:\foo\bar" "C:\foo\bar2\"
```
means exactly to copy "C:\foo\bar" directory INTO "C:\foo\bar2\" - last slash means INTO , so finally we will have "C:\foo\bar2\bar" directory

```
copy "C:\foo\bar" "C:\foo\bar2"
```
without last slash means to get a copy of "C:\foo\bar" next to it and name it "bar2" and get "C:\foo\bar2" with contents of "C:\foo\bar"

Sorry if I can not explain more clearly... But that last slash trick removes any not obvious and undesirable results without having to prompt user for what was expected and such things.

I write this just as idea... maybe Yori's copy/move programs may follow the same path by default or maybe with additional switch like "-a" for advanced target interpretation or something like that.

**Comment by malxau** [comment]
For the issue of `move` overwriting existing files, I pushed commit 414c9827417c40e0d2f56a48fc37ed9ec3cc00be which adds a `-k` option to keep existing files and not overwrite them.  In addition, this causes the `move` command to fail if it didn't successfully move any files.  I'm not sure what to do if it successfully moves one thing and fails to move another.

As far as trailing slash semantics, note that `/s` is indicating whether to operate on directories or files only (as CMD would do.)  Retrofitting directory copies into something similar to CMD was a little clumsy.  The current behaviors here are:

- `copy source dest` (no `/s`, not recursive, dest exists) will copy the contents of the source directory into the dest directory (follows `CMD`);
- `copy source dest` (no `/s`, not recursive, dest does not exist) is only copying files rather than directories, so it copies the contents of source into a file called dest and fails if source contains more than one file (`CMD` would append the files into a single file);
- `copy /s source dest` (recursive, dest exists) will copy the source directory and its contents into the dest directory, so the result will include a "dest\source" directory (`xcopy` will copy the contents of source into dest, so no "dest\source" directory);
- `copy /s source dest` (recursive, dest does not exist) creates dest and a source subdirectory under it (`xcopy` prompts to create a file or subdirectory, but copies the contents of source, so no "dest\source" directory);
- `copy /s source\* dest` (recursive, dest exists) will copy the contents of the source directory into the dest directory, similar to the first case and `xcopy`'s behavior
- `copy /s source\* dest` (recursive, dest does not exist) creates dest and copies the contents of the source directory into the dest directory, similar to the first case and `xcopy`'s behavior.

So when copy is operating with directories, as indicated by `/s`, I think yori has something functionally equivalent expressed by `\*` on the source as opposed to `\` on the target.  This seemed like the clearest thing I could do to express the concept, and using a trailing `\` on the destination would be more obscure and harder for people to understand than the current behavior.  If anything I wish the behavior here could be more obvious and clear - I had to try each of these combinations to write this message, so even now, `copy /s source dest` has behavior that's not immediately obvious.  It's interesting that `xcopy` clearly struggled with this too, which is why by default it prompts the user for the behavior they want.

**Comment by aleaksunder** [comment]
Thanks for the "-k" for MOVE! And IMHO if it moves one thing and fails with another - ERRORLEVEL must be raised but maybe with another result as 2 or 3

And after all I can totally agree : `\*` for source is the same thing as trailing slash for target, there is nothing to do here
