### ISSUE TITLE
dir showing everything

### ISSUE THREAD

**Issue by tmottabr** [malxau/yori#9]
is there a way to have dir not show all the hidden and system stuff by default? like how cmd dir works.

**Comment by malxau** [comment]
Not currently, although sdir can.  It should be simple to implement though.  Out of interest, can I ask why this is useful to you?  When are you using hidden or system attributes?  I've been seeing these as obsolete, since in DOS with no real file system protection they existed to suggest to the user which objects shouldn't be manipulated, but today we have much more forceful mechanisms such as TrustedInstaller.

**Comment by tmottabr** [comment]
i don't use it, just find annoying all the hidden and specially the system stuff that i don't need on a regular basis showing up every time i use dir.

**Comment by malxau** [comment]
I just pushed commit 9249c36c2022a874e7055216ef5297c0a6028f25 to master for this.  Note that in yori commands like "dir" are really aliases, in this case to "ydir $*$".  So if you'd like this to be default behavior, use "alias dir=ydir -h $*$" .

**Comment by malxau** [comment]
This was just released in stable version 1.11.  Let me know if there are any issues.
